apiVersion: apps/v1
kind: Deployment
metadata:
  name: guestbook-ui-prod
spec:
  replicas: 2
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: guestbook-ui-prod
  template:
    metadata:
      labels:
        app: guestbook-ui-prod
    spec:
      containers:
      - image: gcr.io/heptio-images/ks-guestbook-demo:0.2
        name: guestbook-ui-prod
        resources:
      requests:
        cpu: "1"
        memory: "100Mi"
      limits:
        cpu: "0.5"
        memory: "200Mi"

        ports:
        - containerPort: 80
